package com.hepdd.easytech.api.enums;

public enum ETHTextures {

    MACHINE_CASING_COKEOVEN(2688),
    MACHINE_CASING_COKEOVEN_INACTIVE(2689),
    MACHINE_CASING_COKEOVEN_ACTIVE(2690),

    MACHINE_CASING_PRIMITIVE_BLASE_FURNACE(2691),
    MACHINE_CASING_PRIMITIVE_BLASE_FURNACE_INACTIVE(2692),
    MACHINE_CASING_PRIMITIVE_BLASE_FURNACE_ACTIVE(2693),
    MACHINE_CASING_PRIMITIVE_BLASE_FURNACE_ACTIVE_GLOW(2694),

    MACHINE_CASING_VOID_MINER_WOOD(2695),

    ;

    public final int ID;

    ETHTextures(int ID) {
        this.ID = ID;
    }
}
